#------------------------------------------------------------
# LLNL Pascal/Quartz Slurm
#------------------------------------------------------------
---
snippets: "/snippets_library/LLNL_Pascal_slurm"

local:
  prompt: "[user@laptop ~]$"
  bash_shebang: "#!/usr/bin/bash"

remote:
  name: "Pascal"
  login: "pascal.llnl.gov"
  host: "pascal83"
  node: "pascal17"
  location: "Lawrence Livermore National Laboratory"
  homedir: "/g/g0/"
  user: "yourUsername"
  prompt: "yourUsername@pascal83 $"
  bash_shebang: "#!/bin/bash"

sched:
  name: "Slurm"
  submit:
    name: "sbatch"
    options: "--partition=pvis"
  queue:
    debug: "pdebug"
    testing: "pvis"
  status: "squeue"
  flag:
    user: "-u yourUsername"
    interactive: ""
    histdetail: "--format=JobName,Submit,Start,State,ReqCPUS,Reserved,Elapsed,MaxRSS -j"
    name: "-J"
    time: "-t"
    queue: "-p"
    partition: "-p pdebug"
  del: "scancel"
  interactive: "srun"
  info: "sinfo"
  comment: "#SBATCH"
  hist: "sacct -u yourUsername"
  hist_filter: ""

episode_order:
  - 10-hpc-intro
  - 11-connecting
  - 12-cluster
  - 13-scheduler
  - 14-environment-variables
  - 16-transferring-files
  - 17-parallel
  - 18-resources
  - 19-responsibility
